#!/bin/bash

sed -i 's/\[..\]/<img class="smiley" src="smileys\/transformer.gif" alt="smiley"\/>/g' $1
sed -i 's/:BZ/<img class="smiley" src="smileys\/115.gif" alt="smiley"\/>/g' $1
sed -i 's/:bZ/<img class="smiley" src="smileys\/115.gif" alt="smiley"\/>/g' $1
sed -i 's/:Bz/<img class="smiley" src="smileys\/115.gif" alt="smiley"\/>/g' $1
sed -i 's/:bz/<img class="smiley" src="smileys\/115.gif" alt="smiley"\/>/g' $1
sed -i 's/\^#(^/<img class="smiley" src="smileys\/114.gif" alt="smiley"\/>/g' $1
sed -i 's/:-Bd/<img class="smiley" src="smileys\/113.gif" alt="smiley"\/>/g' $1
sed -i 's/:-bD/<img class="smiley" src="smileys\/113.gif" alt="smiley"\/>/g' $1
sed -i 's/:-bd/<img class="smiley" src="smileys\/113.gif" alt="smiley"\/>/g' $1
sed -i 's/:-BD/<img class="smiley" src="smileys\/113.gif" alt="smiley"\/>/g' $1
sed -i 's/:-q/<img class="smiley" src="smileys\/112.gif" alt="smiley"\/>/g' $1
sed -i 's/:-Q/<img class="smiley" src="smileys\/112.gif" alt="smiley"\/>/g' $1
sed -i 's/\\m\//<img class="smiley" src="smileys\/111.gif" alt="smiley"\/>/g' $1
sed -i 's/\\M\//<img class="smiley" src="smileys\/111.gif" alt="smiley"\/>/g' $1
sed -i 's/:!!/<img class="smiley" src="smileys\/110.gif" alt="smiley"\/>/g' $1
sed -i 's/x_x/<img class="smiley" src="smileys\/109.gif" alt="smiley"\/>/g' $1
sed -i 's/X_x/<img class="smiley" src="smileys\/109.gif" alt="smiley"\/>/g' $1
sed -i 's/x_x/<img class="smiley" src="smileys\/109.gif" alt="smiley"\/>/g' $1
sed -i 's/X_X/<img class="smiley" src="smileys\/109.gif" alt="smiley"\/>/g' $1
sed -i 's/:o3/<img class="smiley" src="smileys\/108.gif" alt="smiley"\/>/g' $1
sed -i 's/:O3/<img class="smiley" src="smileys\/108.gif" alt="smiley"\/>/g' $1
sed -i 's/%-(/<img class="smiley" src="smileys\/107.gif" alt="smiley"\/>/g' $1
sed -i 's/:-??/<img class="smiley" src="smileys\/106.gif" alt="smiley"\/>/g' $1
sed -i 's/8->/<img class="smiley" src="smileys\/105.gif" alt="smiley"\/>/g' $1
sed -i 's/:-t/<img class="smiley" src="smileys\/104.gif" alt="smiley"\/>/g' $1
sed -i 's/:-T/<img class="smiley" src="smileys\/104.gif" alt="smiley"\/>/g' $1
sed -i 's/:-h/<img class="smiley" src="smileys\/103.gif" alt="smiley"\/>/g' $1
sed -i 's/:-H/<img class="smiley" src="smileys\/103.gif" alt="smiley"\/>/g' $1
sed -i 's/~x(/<img class="smiley" src="smileys\/102.gif" alt="smiley"\/>/g' $1
sed -i 's/~X(/<img class="smiley" src="smileys\/102.gif" alt="smiley"\/>/g' $1
sed -i 's/:-c/<img class="smiley" src="smileys\/101.gif" alt="smiley"\/>/g' $1
sed -i 's/:-C/<img class="smiley" src="smileys\/101.gif" alt="smiley"\/>/g' $1
sed -i 's/:)\]/<img class="smiley" src="smileys\/100.gif" alt="smiley"\/>/g' $1
sed -i 's/(\*)/<img class="smiley" src="smileys\/79.gif" alt="smiley"\/>/g' $1
sed -i 's/:-j/<img class="smiley" src="smileys\/78.gif" alt="smiley"\/>/g' $1
sed -i 's/:-J/<img class="smiley" src="smileys\/78.gif" alt="smiley"\/>/g' $1
sed -i 's/\^:)^/<img class="smiley" src="smileys\/77.gif" alt="smiley"\/>/g' $1
sed -i 's/:-@/<img class="smiley" src="smileys\/76.gif" alt="smiley"\/>/g' $1
sed -i 's/(%)/<img class="smiley" src="smileys\/75.gif" alt="smiley"\/>/g' $1
sed -i 's/;))/<img class="smiley" src="smileys\/71.gif" alt="smiley"\/>/g' $1
sed -i 's/>:\//<img class="smiley" src="smileys\/70.gif" alt="smiley"\/>/g' $1
sed -i 's/\\:d\//<img class="smiley" src="smileys\/69.gif" alt="smiley"\/>/g' $1
sed -i 's/\\:D\//<img class="smiley" src="smileys\/69.gif" alt="smiley"\/>/g' $1
sed -i 's/\[-x/<img class="smiley" src="smileys\/68.gif" alt="smiley"\/>/g' $1
sed -i 's/\[-X/<img class="smiley" src="smileys\/68.gif" alt="smiley"\/>/g' $1
sed -i 's/:)>-/<img class="smiley" src="smileys\/67.gif" alt="smiley"\/>/g' $1
sed -i 's/b-(/<img class="smiley" src="smileys\/66.gif" alt="smiley"\/>/g' $1
sed -i 's/B-(/<img class="smiley" src="smileys\/66.gif" alt="smiley"\/>/g' $1
sed -i 's/:-"/<img class="smiley" src="smileys\/65.gif" alt="smiley"\/>/g' $1
sed -i 's/$-)/<img class="smiley" src="smileys\/64.gif" alt="smiley"\/>/g' $1
sed -i 's/\[-o</<img class="smiley" src="smileys\/63.gif" alt="smiley"\/>/g' $1
sed -i 's/\[-O</<img class="smiley" src="smileys\/63.gif" alt="smiley"\/>/g' $1
sed -i 's/:-l/<img class="smiley" src="smileys\/62.gif" alt="smiley"\/>/g' $1
sed -i 's/:-L/<img class="smiley" src="smileys\/62.gif" alt="smiley"\/>/g' $1
sed -i 's/>-)/<img class="smiley" src="smileys\/61.gif" alt="smiley"\/>/g' $1
sed -i 's/=:)/<img class="smiley" src="smileys\/60.gif" alt="smiley"\/>/g' $1
sed -i 's/8-x/<img class="smiley" src="smileys\/59.gif" alt="smiley"\/>/g' $1
sed -i 's/8-X/<img class="smiley" src="smileys\/59.gif" alt="smiley"\/>/g' $1
sed -i 's/\*-:)/<img class="smiley" src="smileys\/58.gif" alt="smiley"\/>/g' $1
sed -i 's/~o)/<img class="smiley" src="smileys\/57.gif" alt="smiley"\/>/g' $1
sed -i 's/~O)/<img class="smiley" src="smileys\/57.gif" alt="smiley"\/>/g' $1
sed -i 's/(~~)/<img class="smiley" src="smileys\/56.gif" alt="smiley"\/>/g' $1
sed -i 's/\*\*==/<img class="smiley" src="smileys\/55.gif" alt="smiley"\/>/g' $1
sed -i 's/%%-/<img class="smiley" src="smileys\/54.gif" alt="smiley"\/>/g' $1
sed -i 's/@};/<img class="smiley" src="smileys\/53.gif" alt="smiley"\/>/g' $1
sed -i 's/~:>/<img class="smiley" src="smileys\/52.gif" alt="smiley"\/>/g' $1
sed -i 's/:(|)/<img class="smiley" src="smileys\/51.gif" alt="smiley"\/>/g' $1
sed -i 's/3:-o/<img class="smiley" src="smileys\/50.gif" alt="smiley"\/>/g' $1
sed -i 's/3:-O/<img class="smiley" src="smileys\/50.gif" alt="smiley"\/>/g' $1
sed -i 's/:@)/<img class="smiley" src="smileys\/49.gif" alt="smiley"\/>/g' $1
sed -i 's/<):)/<img class="smiley" src="smileys\/48.gif" alt="smiley"\/>/g' $1
sed -i 's/>:p/<img class="smiley" src="smileys\/47.gif" alt="smiley"\/>/g' $1
sed -i 's/>:P/<img class="smiley" src="smileys\/47.gif" alt="smiley"\/>/g' $1
sed -i 's/:-</<img class="smiley" src="smileys\/46.gif" alt="smiley"\/>/g' $1
sed -i 's/:-w/<img class="smiley" src="smileys\/45.gif" alt="smiley"\/>/g' $1
sed -i 's/:-W/<img class="smiley" src="smileys\/45.gif" alt="smiley"\/>/g' $1
sed -i 's/:^o/<img class="smiley" src="smileys\/44.gif" alt="smiley"\/>/g' $1
sed -i 's/:^O/<img class="smiley" src="smileys\/44.gif" alt="smiley"\/>/g' $1
sed -i 's/@-)/<img class="smiley" src="smileys\/43.gif" alt="smiley"\/>/g' $1
sed -i 's/:-sS/<img class="smiley" src="smileys\/42.gif" alt="smiley"\/>/g' $1
sed -i 's/:-Ss/<img class="smiley" src="smileys\/42.gif" alt="smiley"\/>/g' $1
sed -i 's/:-ss/<img class="smiley" src="smileys\/42.gif" alt="smiley"\/>/g' $1
sed -i 's/:-SS/<img class="smiley" src="smileys\/42.gif" alt="smiley"\/>/g' $1
sed -i 's/=d>/<img class="smiley" src="smileys\/41.gif" alt="smiley"\/>/g' $1
sed -i 's/=D>/<img class="smiley" src="smileys\/41.gif" alt="smiley"\/>/g' $1
sed -i 's/#-o/<img class="smiley" src="smileys\/40.gif" alt="smiley"\/>/g' $1
sed -i 's/#-O/<img class="smiley" src="smileys\/40.gif" alt="smiley"\/>/g' $1
sed -i 's/:-?/<img class="smiley" src="smileys\/39.gif" alt="smiley"\/>/g' $1
sed -i 's/=p~/<img class="smiley" src="smileys\/38.gif" alt="smiley"\/>/g' $1
sed -i 's/=P~/<img class="smiley" src="smileys\/38.gif" alt="smiley"\/>/g' $1
sed -i 's/(:|/<img class="smiley" src="smileys\/37.gif" alt="smiley"\/>/g' $1
sed -i 's/<:-p/<img class="smiley" src="smileys\/36.gif" alt="smiley"\/>/g' $1
sed -i 's/<:-P/<img class="smiley" src="smileys\/36.gif" alt="smiley"\/>/g' $1
sed -i 's/8-}/<img class="smiley" src="smileys\/35.gif" alt="smiley"\/>/g' $1
sed -i 's/:o)/<img class="smiley" src="smileys\/34.gif" alt="smiley"\/>/g' $1
sed -i 's/:O)/<img class="smiley" src="smileys\/34.gif" alt="smiley"\/>/g' $1
sed -i 's/\[-(/<img class="smiley" src="smileys\/33.gif" alt="smiley"\/>/g' $1
sed -i 's/:-\$/<img class="smiley" src="smileys\/32.gif" alt="smiley"\/>/g' $1
sed -i 's/:-&/<img class="smiley" src="smileys\/31.gif" alt="smiley"\/>/g' $1
sed -i 's/l-)/<img class="smiley" src="smileys\/30.gif" alt="smiley"\/>/g' $1
sed -i 's/L-)/<img class="smiley" src="smileys\/30.gif" alt="smiley"\/>/g' $1
sed -i 's/8-|/<img class="smiley" src="smileys\/29.gif" alt="smiley"\/>/g' $1
sed -i 's/i-)/<img class="smiley" src="smileys\/28.gif" alt="smiley"\/>/g' $1
sed -i 's/I-)/<img class="smiley" src="smileys\/28.gif" alt="smiley"\/>/g' $1
sed -i 's/=,/<img class="smiley" src="smileys\/27.gif" alt="smiley"\/>/g' $1
sed -i 's/:-b/<img class="smiley" src="smileys\/26.gif" alt="smiley"\/>/g' $1
sed -i 's/:-B/<img class="smiley" src="smileys\/26.gif" alt="smiley"\/>/g' $1
sed -i 's/o:)/<img class="smiley" src="smileys\/25.gif" alt="smiley"\/>/g' $1
sed -i 's/O:)/<img class="smiley" src="smileys\/25.gif" alt="smiley"\/>/g' $1
sed -i 's/o:-)/<img class="smiley" src="smileys\/25.gif" alt="smiley"\/>/g' $1
sed -i 's/O:-)/<img class="smiley" src="smileys\/25.gif" alt="smiley"\/>/g' $1
sed -i 's/=))/<img class="smiley" src="smileys\/24.gif" alt="smiley"\/>/g' $1
sed -i 's/\/:)/<img class="smiley" src="smileys\/23.gif" alt="smiley"\/>/g' $1
sed -i 's/:|/<img class="smiley" src="smileys\/22.gif" alt="smiley"\/>/g' $1
sed -i 's/:))/<img class="smiley" src="smileys\/21.gif" alt="smiley"\/>/g' $1
sed -i 's/:((/<img class="smiley" src="smileys\/20.gif" alt="smiley"\/>/g' $1
sed -i 's/>:)/<img class="smiley" src="smileys\/19.gif" alt="smiley"\/>/g' $1
sed -i 's/#:-s/<img class="smiley" src="smileys\/18.gif" alt="smiley"\/>/g' $1
sed -i 's/#:-S/<img class="smiley" src="smileys\/18.gif" alt="smiley"\/>/g' $1
sed -i 's/:-s/<img class="smiley" src="smileys\/17.gif" alt="smiley"\/>/g' $1
sed -i 's/:-S/<img class="smiley" src="smileys\/17.gif" alt="smiley"\/>/g' $1
sed -i 's/b-)/<img class="smiley" src="smileys\/16.gif" alt="smiley"\/>/g' $1
sed -i 's/B-)/<img class="smiley" src="smileys\/16.gif" alt="smiley"\/>/g' $1
sed -i 's/:>/<img class="smiley" src="smileys\/15.gif" alt="smiley"\/>/g' $1
sed -i 's/:->/<img class="smiley" src="smileys\/15.gif" alt="smiley"\/>/g' $1
sed -i 's/x-(/<img class="smiley" src="smileys\/14.gif" alt="smiley"\/>/g' $1
sed -i 's/X-(/<img class="smiley" src="smileys\/14.gif" alt="smiley"\/>/g' $1
sed -i 's/x(/<img class="smiley" src="smileys\/14.gif" alt="smiley"\/>/g' $1
sed -i 's/X(/<img class="smiley" src="smileys\/14.gif" alt="smiley"\/>/g' $1
sed -i 's/:o/<img class="smiley" src="smileys\/13.gif" alt="smiley"\/>/g' $1
sed -i 's/:O/<img class="smiley" src="smileys\/13.gif" alt="smiley"\/>/g' $1
sed -i 's/:-o/<img class="smiley" src="smileys\/13.gif" alt="smiley"\/>/g' $1
sed -i 's/:-O/<img class="smiley" src="smileys\/13.gif" alt="smiley"\/>/g' $1
sed -i 's/=((/<img class="smiley" src="smileys\/12.gif" alt="smiley"\/>/g' $1
sed -i 's/:\*/<img class="smiley" src="smileys\/11.gif" alt="smiley"\/>/g' $1
sed -i 's/:-\*/<img class="smiley" src="smileys\/11.gif" alt="smiley"\/>/g' $1
sed -i 's/:-p/<img class="smiley" src="smileys\/10.gif" alt="smiley"\/>/g' $1
sed -i 's/:-P/<img class="smiley" src="smileys\/10.gif" alt="smiley"\/>/g' $1
sed -i 's/:p/<img class="smiley" src="smileys\/10.gif" alt="smiley"\/>/g' $1
sed -i 's/:P/<img class="smiley" src="smileys\/10.gif" alt="smiley"\/>/g' $1
sed -i 's/:">/<img class="smiley" src="smileys\/9.gif" alt="smiley"\/>/g' $1
sed -i 's/:-x/<img class="smiley" src="smileys\/8.gif" alt="smiley"\/>/g' $1
sed -i 's/:-X/<img class="smiley" src="smileys\/8.gif" alt="smiley"\/>/g' $1
sed -i 's/:x/<img class="smiley" src="smileys\/8.gif" alt="smiley"\/>/g' $1
sed -i 's/:X/<img class="smiley" src="smileys\/8.gif" alt="smiley"\/>/g' $1
sed -i 's/:-\//<img class="smiley" src="smileys\/7.gif" alt="smiley"\/>/g' $1
sed -i 's/>:d</<img class="smiley" src="smileys\/6.gif" alt="smiley"\/>/g' $1
sed -i 's/>:D</<img class="smiley" src="smileys\/6.gif" alt="smiley"\/>/g' $1
sed -i 's/;;)/<img class="smiley" src="smileys\/5.gif" alt="smiley"\/>/g' $1
sed -i 's/:-d/<img class="smiley" src="smileys\/4.gif" alt="smiley"\/>/g' $1
sed -i 's/:-D/<img class="smiley" src="smileys\/4.gif" alt="smiley"\/>/g' $1
sed -i 's/:d/<img class="smiley" src="smileys\/4.gif" alt="smiley"\/>/g' $1
sed -i 's/:D/<img class="smiley" src="smileys\/4.gif" alt="smiley"\/>/g' $1
sed -i 's/;-)/<img class="smiley" src="smileys\/3.gif" alt="smiley"\/>/g' $1
sed -i 's/;)/<img class="smiley" src="smileys\/3.gif" alt="smiley"\/>/g' $1
sed -i 's/:-(/<img class="smiley" src="smileys\/2.gif" alt="smiley"\/>/g' $1
sed -i 's/:(/<img class="smiley" src="smileys\/2.gif" alt="smiley"\/>/g' $1
sed -i 's/:-)/<img class="smiley" src="smileys\/1.gif" alt="smiley"\/>/g' $1
sed -i 's/:)/<img class="smiley" src="smileys\/1.gif" alt="smiley"\/>/g' $1
